/*
 * OpenProdoc
 * 
 * See the help doc files distributed with
 * this work for additional information regarding copyright ownership.
 * Joaquin Hierro licenses this file to You under:
 * 
 * License GNU GPL v3 http://www.gnu.org/licenses/gpl.html
 * 
 * you may not use this file except in compliance with the License.  
 * Unless agreed to in writing, software is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * author: Joaquin Hierro      2011
 * 
 */

package prodocswing.forms;

import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import prodoc.*;
import prodocswing.PDTableModel;
import prodocswing.TreeTerm;

/**
 *
 * @author jhierrot
 */
public class MainThes extends javax.swing.JDialog
{

private static DriverGeneric Session=null;
private DefaultTreeModel TermTreeModel=null;
private String ActTermId=null;
private PDThesaur TermAct=null;
private PDTableModel NTMembers;
private PDTableModel RTMembers;
private PDTableModel LangMembers;
private PDTableModel UFMembers;
private Vector VEmpty=new Vector();
private int DividerLocRel=100, DividerLocTerm=100;

private String IdLocalRootTerm=PDThesaur.ROOTTERM;
boolean ShowDet=true;
/**
 * Creates new form MainThes
 * @param parent
 * @param modal 
 * @param Sess  
 */
public MainThes(java.awt.Frame parent, boolean modal, DriverGeneric Sess)
{
super(parent, modal);
Session=Sess;
initComponents();
}
/**
 * Creates new form MainThes
 * @param parent
 * @param modal
 * @param Sess 
 * @param RootTerm  
 */
public MainThes(JDialog parent, boolean modal, DriverGeneric Sess, String RootTerm)
{
super(parent, modal);
setIdLocalRootTerm(RootTerm);
Session=Sess;
initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreeTerm = new javax.swing.JTree();
        DetailsPanel = new javax.swing.JSplitPane();
        TermAttr = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        DescripLabel = new javax.swing.JLabel();
        DescripTextField = new javax.swing.JTextField();
        UseLabel = new javax.swing.JLabel();
        UseTextField = new javax.swing.JTextField();
        SCNLabel = new javax.swing.JLabel();
        LangTextField = new javax.swing.JTextField();
        SCNTextField = new javax.swing.JTextField();
        LangLabel = new javax.swing.JLabel();
        Relations = new javax.swing.JTabbedPane();
        jPanelRT = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        RTTable = new javax.swing.JTable();
        jPanelLang = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        LangTable = new javax.swing.JTable();
        jPanelUF = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        UFTable = new javax.swing.JTable();
        jPanelNT = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NTTable = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        ThesaurMenu = new javax.swing.JMenu();
        AddThesaur = new javax.swing.JMenuItem();
        UpdateThesaur = new javax.swing.JMenuItem();
        DelThesaur = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        RefreshTerm = new javax.swing.JMenuItem();
        ExportThes = new javax.swing.JMenuItem();
        ImportThes = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        TermMenu = new javax.swing.JMenu();
        AddTerm = new javax.swing.JMenuItem();
        ModTerm = new javax.swing.JMenuItem();
        DelTerm = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        SearchTerm1 = new javax.swing.JMenuItem();
        Selecting = new javax.swing.JMenu();
        Select = new javax.swing.JMenuItem();
        ShowDetails = new javax.swing.JCheckBoxMenuItem();
        ShowChild = new javax.swing.JCheckBoxMenuItem();
        helpMenu = new javax.swing.JMenu();
        ThesaurHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(4);

        TreeTerm.setFont(getFontTree());
        TreeTerm.setModel(getTreeModel());
        TreeTerm.setAlignmentX(0.3F);
        TreeTerm.setAutoscrolls(true);
        TreeTerm.setMaximumSize(new java.awt.Dimension(400, 76));
        TreeTerm.setMinimumSize(new java.awt.Dimension(200, 60));
        TreeTerm.setPreferredSize(new java.awt.Dimension(200, 76));
        TreeTerm.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener()
        {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt)
            {
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt)
            {
                TreeTermTreeExpanded(evt);
            }
        });
        TreeTerm.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener()
        {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt)
            {
                TreeTermValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(TreeTerm);

        jSplitPane1.setLeftComponent(jScrollPane1);

        DetailsPanel.setDividerLocation(160);
        DetailsPanel.setDividerSize(4);
        DetailsPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        TermAttr.setMinimumSize(new java.awt.Dimension(100, 100));

        NameLabel.setFont(MainWin.getFontDialog());
        NameLabel.setText("Name");

        NameTextField.setEditable(false);
        NameTextField.setFont(MainWin.getFontDialog());

        DescripLabel.setFont(MainWin.getFontDialog());
        DescripLabel.setText("Descrip");

        DescripTextField.setEditable(false);
        DescripTextField.setFont(MainWin.getFontDialog());

        UseLabel.setFont(MainWin.getFontDialog());
        UseLabel.setText("Use");

        UseTextField.setEditable(false);
        UseTextField.setFont(MainWin.getFontDialog());

        SCNLabel.setFont(MainWin.getFontDialog());
        SCNLabel.setText("SCN");

        LangTextField.setEditable(false);
        LangTextField.setFont(MainWin.getFontDialog());

        SCNTextField.setEditable(false);
        SCNTextField.setFont(MainWin.getFontDialog());

        LangLabel.setFont(MainWin.getFontDialog());
        LangLabel.setText("Language");

        javax.swing.GroupLayout TermAttrLayout = new javax.swing.GroupLayout(TermAttr);
        TermAttr.setLayout(TermAttrLayout);
        TermAttrLayout.setHorizontalGroup(
            TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TermAttrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TermAttrLayout.createSequentialGroup()
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TermAttrLayout.createSequentialGroup()
                        .addComponent(DescripLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescripTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TermAttrLayout.createSequentialGroup()
                        .addComponent(UseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TermAttrLayout.createSequentialGroup()
                        .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LangLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(SCNLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SCNTextField))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TermAttrLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DescripLabel, LangLabel, NameLabel, SCNLabel, UseLabel});

        TermAttrLayout.setVerticalGroup(
            TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TermAttrLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescripTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescripLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TermAttrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SCNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        TermAttrLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DescripLabel, LangLabel, NameLabel, SCNLabel, UseLabel});

        DetailsPanel.setLeftComponent(TermAttr);

        jPanelRT.setFont(MainWin.getFontDialog());

        RTTable.setFont(MainWin.getFontList());
        RTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(RTTable);

        javax.swing.GroupLayout jPanelRTLayout = new javax.swing.GroupLayout(jPanelRT);
        jPanelRT.setLayout(jPanelRTLayout);
        jPanelRTLayout.setHorizontalGroup(
            jPanelRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanelRTLayout.setVerticalGroup(
            jPanelRTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        Relations.addTab("RT", jPanelRT);

        jPanelLang.setFont(MainWin.getFontDialog());

        LangTable.setFont(MainWin.getFontList());
        LangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(LangTable);

        javax.swing.GroupLayout jPanelLangLayout = new javax.swing.GroupLayout(jPanelLang);
        jPanelLang.setLayout(jPanelLangLayout);
        jPanelLangLayout.setHorizontalGroup(
            jPanelLangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanelLangLayout.setVerticalGroup(
            jPanelLangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        Relations.addTab("Lang", jPanelLang);

        jPanelUF.setFont(MainWin.getFontDialog());

        UFTable.setFont(MainWin.getFontList());
        UFTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(UFTable);

        javax.swing.GroupLayout jPanelUFLayout = new javax.swing.GroupLayout(jPanelUF);
        jPanelUF.setLayout(jPanelUFLayout);
        jPanelUFLayout.setHorizontalGroup(
            jPanelUFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanelUFLayout.setVerticalGroup(
            jPanelUFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        Relations.addTab("UF", jPanelUF);

        jPanelNT.setFont(MainWin.getFontDialog());

        NTTable.setFont(MainWin.getFontList());
        NTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(NTTable);

        javax.swing.GroupLayout jPanelNTLayout = new javax.swing.GroupLayout(jPanelNT);
        jPanelNT.setLayout(jPanelNTLayout);
        jPanelNTLayout.setHorizontalGroup(
            jPanelNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanelNTLayout.setVerticalGroup(
            jPanelNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        Relations.addTab("NT", jPanelNT);

        DetailsPanel.setRightComponent(Relations);

        jSplitPane1.setRightComponent(DetailsPanel);

        menuBar.setFont(getFontMenu());

        ThesaurMenu.setText(MainWin.DrvTT("Thesaurus"));
        ThesaurMenu.setFont(getFontMenu());

        AddThesaur.setFont(getFontMenu());
        AddThesaur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        AddThesaur.setText(MainWin.DrvTT("Create_Theusurus"));
        AddThesaur.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddThesaurActionPerformed(evt);
            }
        });
        ThesaurMenu.add(AddThesaur);

        UpdateThesaur.setFont(getFontMenu());
        UpdateThesaur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        UpdateThesaur.setText(MainWin.DrvTT("Update_Thesaurus"));
        UpdateThesaur.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UpdateThesaurActionPerformed(evt);
            }
        });
        ThesaurMenu.add(UpdateThesaur);

        DelThesaur.setFont(getFontMenu());
        DelThesaur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/del.png"))); // NOI18N
        DelThesaur.setText(MainWin.DrvTT("Delete_Thesaurus"));
        DelThesaur.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DelThesaurActionPerformed(evt);
            }
        });
        ThesaurMenu.add(DelThesaur);
        ThesaurMenu.add(jSeparator2);

        RefreshTerm.setFont(getFontMenu());
        RefreshTerm.setText(MainWin.DrvTT("Refresh"));
        RefreshTerm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RefreshTermActionPerformed(evt);
            }
        });
        ThesaurMenu.add(RefreshTerm);

        ExportThes.setFont(getFontMenu());
        ExportThes.setText(MainWin.DrvTT("Export_Thesaurus"));
        ExportThes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ExportThesActionPerformed(evt);
            }
        });
        ThesaurMenu.add(ExportThes);

        ImportThes.setFont(getFontMenu());
        ImportThes.setText(MainWin.DrvTT("Import_Thesaurus"));
        ImportThes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ImportThesActionPerformed(evt);
            }
        });
        ThesaurMenu.add(ImportThes);
        ThesaurMenu.add(jSeparator6);

        exitMenuItem.setFont(getFontMenu());
        exitMenuItem.setText(MainWin.DrvTT("Close_Window"));
        exitMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitMenuItemActionPerformed(evt);
            }
        });
        ThesaurMenu.add(exitMenuItem);

        menuBar.add(ThesaurMenu);

        TermMenu.setText(MainWin.DrvTT("Terms"));
        TermMenu.setFont(getFontMenu());

        AddTerm.setFont(getFontMenu());
        AddTerm.setText(MainWin.DrvTT("Add_Term"));
        AddTerm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddTermActionPerformed(evt);
            }
        });
        TermMenu.add(AddTerm);

        ModTerm.setFont(getFontMenu());
        ModTerm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        ModTerm.setText(MainWin.DrvTT("Update_Term"));
        ModTerm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModTermActionPerformed(evt);
            }
        });
        TermMenu.add(ModTerm);

        DelTerm.setFont(getFontMenu());
        DelTerm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/del.png"))); // NOI18N
        DelTerm.setText(MainWin.DrvTT("Delete_Term"));
        DelTerm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DelTermActionPerformed(evt);
            }
        });
        TermMenu.add(DelTerm);
        TermMenu.add(jSeparator3);

        SearchTerm1.setFont(getFontMenu());
        SearchTerm1.setText(MainWin.DrvTT("Search_Terms"));
        SearchTerm1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SearchTerm1ActionPerformed(evt);
            }
        });
        TermMenu.add(SearchTerm1);

        menuBar.add(TermMenu);

        Selecting.setText(MainWin.DrvTT("Selection"));
        Selecting.setFont(getFontMenu());

        Select.setFont(getFontMenu());
        Select.setText(MainWin.DrvTT("Select_Term"));
        Select.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SelectActionPerformed(evt);
            }
        });
        Selecting.add(Select);

        ShowDetails.setFont(getFontMenu());
        ShowDetails.setSelected(true);
        ShowDetails.setText(MainWin.DrvTT("Show_details"));
        ShowDetails.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ShowDetailsActionPerformed(evt);
            }
        });
        Selecting.add(ShowDetails);

        ShowChild.setFont(getFontMenu());
        ShowChild.setSelected(true);
        ShowChild.setText(MainWin.DrvTT("Show_Childs"));
        ShowChild.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ShowChildActionPerformed(evt);
            }
        });
        Selecting.add(ShowChild);

        menuBar.add(Selecting);

        helpMenu.setText(MainWin.DrvTT("Help"));
        helpMenu.setFont(getFontMenu());

        ThesaurHelp.setFont(getFontMenu());
        ThesaurHelp.setText(MainWin.DrvTT("Thesaurus_MainWin"));
        ThesaurHelp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ThesaurHelpActionPerformed(evt);
            }
        });
        helpMenu.add(ThesaurHelp);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddThesaurActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddThesaurActionPerformed
    {//GEN-HEADEREND:event_AddThesaurActionPerformed
try {
MantThes MTF = new MantThes(this, true);
MTF.setLocationRelativeTo(null);
MTF.setRecord(PDThesaur.getRecordStructPDThesaur());
MTF.AddMode();
MTF.setVisible(true);
if (MTF.isCancel())
return;
PDThesaur Term=new PDThesaur(Session);
Term.assignValues(MTF.getRecord());
Term.setParentId(PDThesaur.ROOTTERM);
Term.insert();
TreePath ActualPath = TreeTerm.getSelectionPath();
ExpandFold((DefaultMutableTreeNode)ActualPath.getPath()[0]);
TreeTerm.setSelectionPath(ActualPath);
} catch (Exception ex)
    {
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_AddThesaurActionPerformed

    private void UpdateThesaurActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UpdateThesaurActionPerformed
    {//GEN-HEADEREND:event_UpdateThesaurActionPerformed
if (ActTermId.equals(PDThesaur.ROOTTERM))
    return;
try {
TreePath selectionPath = TreeTerm.getSelectionPath();
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
PDThesaur Term= ((TreeTerm) TreeFold.getUserObject()).getTerm();
MantThes MTF = new MantThes(this, true);
MTF.setLocationRelativeTo(null);
MTF.EditMode();
Term.Load(ActTermId);
MTF.setRecord(Term.getRecord());
MTF.setVisible(true);
if (MTF.isCancel())
    return;
ActTermId=Term.getParentId();
Term.assignValues(MTF.getRecord());
Term.update();
TreePath ParentFold = (TreePath) TreeTerm.getSelectionPath().getParentPath();
ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
TreeTerm.setSelectionPath(selectionPath.getParentPath());
TreeFold = (DefaultMutableTreeNode) selectionPath.getParentPath().getLastPathComponent();
            setTermAct(((TreeTerm) TreeFold.getUserObject()).getTerm());
} catch (Exception ex)
    {
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_UpdateThesaurActionPerformed

    private void DelThesaurActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DelThesaurActionPerformed
    {//GEN-HEADEREND:event_DelThesaurActionPerformed
if (ActTermId.equals(PDThesaur.ROOTTERM))
    return;
try {
TreePath selectionPath = TreeTerm.getSelectionPath();
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
PDThesaur Term= ((TreeTerm) TreeFold.getUserObject()).getTerm();
MantThes MTF = new MantThes(this, true);
MTF.setLocationRelativeTo(null);
MTF.DelMode();
Term.Load(ActTermId);
MTF.setRecord(Term.getRecord());
MTF.setVisible(true);
if (MTF.isCancel())
    return;
ActTermId=Term.getParentId();
Term.delete();
TreePath ParentFold = (TreePath) TreeTerm.getSelectionPath().getParentPath();
ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
TreeTerm.setSelectionPath(selectionPath.getParentPath());
TreeFold = (DefaultMutableTreeNode) selectionPath.getParentPath().getLastPathComponent();
            setTermAct(((TreeTerm) TreeFold.getUserObject()).getTerm());
} catch (Exception ex)
    {
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_DelThesaurActionPerformed

    private void RefreshTermActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RefreshTermActionPerformed
    {//GEN-HEADEREND:event_RefreshTermActionPerformed
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) TreeTerm.getSelectionPath().getLastPathComponent();
ExpandFold(TreeFold);
    }//GEN-LAST:event_RefreshTermActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitMenuItemActionPerformed
    {//GEN-HEADEREND:event_exitMenuItemActionPerformed
setTermAct(null);
this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void ThesaurHelpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ThesaurHelpActionPerformed
    {//GEN-HEADEREND:event_ThesaurHelpActionPerformed
MainWin.Execute("doc"+MainWin.OSSep()+MainWin.getLang()+MainWin.OSSep()+"ThesaurWin.html");
    }//GEN-LAST:event_ThesaurHelpActionPerformed

    private void TreeTermTreeExpanded(javax.swing.event.TreeExpansionEvent evt)//GEN-FIRST:event_TreeTermTreeExpanded
    {//GEN-HEADEREND:event_TreeTermTreeExpanded
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
if ( ((TreeTerm) TreeFold.getUserObject()).isExpanded())
    return;
ExpandFold(TreeFold);
    }//GEN-LAST:event_TreeTermTreeExpanded

    private void TreeTermValueChanged(javax.swing.event.TreeSelectionEvent evt)//GEN-FIRST:event_TreeTermValueChanged
    {//GEN-HEADEREND:event_TreeTermValueChanged
try {
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
setTermAct(((TreeTerm) TreeFold.getUserObject()).getTerm());
ActTermId=  getTermAct().getPDId();
this.NameTextField.setText(getTermAct().getName());
this.DescripTextField.setText(getTermAct().getDescription());
if (getTermAct().getUse()!=null && getTermAct().getUse().length()!=0)
    {
    PDThesaur UseTerm=new PDThesaur(Session);
    UseTerm.Load(getTermAct().getUse());
    UseTextField.setText(UseTerm.getName());
    }
else
    UseTextField.setText("");    
this.LangTextField.setText(getTermAct().getLang());
this.SCNTextField.setText(getTermAct().getSCN());
if (ShowDetails.isSelected() && ShowChild.isSelected())
    UpdateTabs(ActTermId);
} catch (Exception ex)
    {
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_TreeTermValueChanged

    private void SelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SelectActionPerformed
    {//GEN-HEADEREND:event_SelectActionPerformed
this.dispose();
    }//GEN-LAST:event_SelectActionPerformed

    private void ShowDetailsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ShowDetailsActionPerformed
    {//GEN-HEADEREND:event_ShowDetailsActionPerformed
if (ShowDetails.isSelected())
    {
    try {
        UpdateTabs(ActTermId);
    } catch (PDException ex)
        {
        MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
        }
    ShowDetails(true);
    }
else
    {    
    ShowDetails(false);    
    }
    }//GEN-LAST:event_ShowDetailsActionPerformed

    private void ShowChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowChildActionPerformed
if (ShowChild.isSelected())
    {
    try {
        UpdateTabs(ActTermId);
    } catch (PDException ex)
        {
        MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
        }
    DetailsPanel.setDividerLocation(DividerLocRel);
    Relations.setVisible(true);    
    }
else
    {    
    DividerLocRel=DetailsPanel.getDividerLocation();
    Relations.setVisible(false);
    }
    }//GEN-LAST:event_ShowChildActionPerformed

    private void AddTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTermActionPerformed
if (ActTermId.equals(getIdLocalRootTerm()))
    return;
MantTerm MTF;
try {
MTF = new MantTerm(this, true, IdLocalRootTerm.equals(PDThesaur.ROOTTERM)?getTermAct().getIDThesaur():IdLocalRootTerm);
MTF.setLocationRelativeTo(null);
MTF.setRecord(PDThesaur.getRecordStructPDThesaur(), getTermAct().getName());
MTF.AddMode();
    } catch (Exception ex)
        {
        MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
        return;
        }    
while (true)
    {
    try {
    MTF.setVisible(true);
    if (MTF.isCancel())
        return;
    PDThesaur Term=new PDThesaur(Session);
    Term.assignValues(MTF.getRecord());
    Term.setParentId(ActTermId);
    Session.IniciarTrans();
    Term.insert();
    Term.AddRT(MTF.getMemRT());
    Term.AddLang(MTF.getMemLang());
    Session.CerrarTrans();
    TreePath ActualPath = TreeTerm.getSelectionPath();
    ExpandFold((DefaultMutableTreeNode)ActualPath.getLastPathComponent());
    TreeTerm.setSelectionPath(ActualPath);
    return;
    } catch (Exception ex)
        {
        MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
        }    
}
    }//GEN-LAST:event_AddTermActionPerformed

    private void ModTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModTermActionPerformed
if (ActTermId.equals(getIdLocalRootTerm()))
    return;
PDThesaur Term;
MantTerm MTF;
TreePath selectionPath;
try {
selectionPath = TreeTerm.getSelectionPath();
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
Term= ((TreeTerm) TreeFold.getUserObject()).getTerm();
Term.Load(Term.getPDId());
if (Term.getParentId().equals(PDThesaur.ROOTTERM))
    return; // trying to edit a Thesaur as term
MTF = new MantTerm(this, true, IdLocalRootTerm.equals(PDThesaur.ROOTTERM)?getTermAct().getIDThesaur():IdLocalRootTerm);
MTF.setLocationRelativeTo(null);
MTF.EditMode();
PDThesaur ParentTerm=new PDThesaur(Session);
ParentTerm.Load(Term.getParentId());
MTF.setRecord(Term.getRecord(), ParentTerm.getName());
    } catch (Exception ex)
        {
        MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
        return;
        }
while (true)
    {
    try {
    MTF.setVisible(true);
    if (MTF.isCancel())
        return;
    Term.assignValues(MTF.getRecord());
    Session.IniciarTrans();
    Term.update();
    Term.DeleteTermRT();
    Term.AddRT(MTF.getMemRT());
    Term.DeleteTermLang();
    Term.AddLang(MTF.getMemLang());
    Session.CerrarTrans();
    TreePath ParentFold = (TreePath) TreeTerm.getSelectionPath().getParentPath();
    ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
    TreeTerm.setSelectionPath(selectionPath);
    return;
    } catch (Exception ex)
        {
        MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
        }
    }

    }//GEN-LAST:event_ModTermActionPerformed

    private void DelTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelTermActionPerformed
if (ActTermId.equals(getIdLocalRootTerm()))
    return;
try {
TreePath selectionPath = TreeTerm.getSelectionPath();
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
PDThesaur Term= ((TreeTerm) TreeFold.getUserObject()).getTerm();
Term.Load(Term.getPDId());
if (Term.getParentId().equals(PDThesaur.ROOTTERM))
    return; // trying to edit a Thesaur as term
MantTerm MTF = new MantTerm(this, true, IdLocalRootTerm.equals(PDThesaur.ROOTTERM)?getTermAct().getIDThesaur():IdLocalRootTerm);
MTF.setLocationRelativeTo(null);
MTF.DelMode();
PDThesaur ParentTerm=new PDThesaur(Session);
ParentTerm.Load(Term.getParentId());
MTF.setRecord(Term.getRecord(), ParentTerm.getName());
MTF.setVisible(true);
if (MTF.isCancel())
    return;
Term.delete();
TreePath ParentFold = (TreePath) TreeTerm.getSelectionPath().getParentPath();
ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
TreeTerm.setSelectionPath(selectionPath);
} catch (Exception ex)
    {
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_DelTermActionPerformed

    private void SearchTerm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTerm1ActionPerformed
SearchThes SF = new SearchThes(this, true);
SF.setLocationRelativeTo(null);
SF.setFoldAct(ActTermId);
SF.setVisible(true);     
    }//GEN-LAST:event_SearchTerm1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
setTermAct(null);
    }//GEN-LAST:event_formWindowClosing

    private void ExportThesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExportThesActionPerformed
    {//GEN-HEADEREND:event_ExportThesActionPerformed
try {   
DialogExportThes ExpThes = new DialogExportThes(this,true);
ExpThes.setLocationRelativeTo(null);
ExpThes.setVisible(true);
if (ExpThes.isCancel())
    return;
setCursor(MainWin.WaitCur);    
PDThesaur Thes=new PDThesaur(Session);
Thes.Export(ActTermId, ExpThes.SelFolder.getAbsolutePath()+File.separatorChar+ActTermId+".rdf.xml", ExpThes.getRoot(), ExpThes.getMainLang());
setCursor(MainWin.DefCur);
} catch (Exception ex)
    {
    setCursor(MainWin.DefCur);    
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ExportThesActionPerformed

    private void ImportThesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ImportThesActionPerformed
    {//GEN-HEADEREND:event_ImportThesActionPerformed
try {   
//DialogExportThes ExpThes = new DialogExportThes(this,true);
//ExpThes.setLocationRelativeTo(null);
//ExpThes.setVisible(true);
//if (ExpThes.isCancel())
//    return;
setCursor(MainWin.WaitCur);    
PDThesaur Thes=new PDThesaur(Session);
// Thes.Export(ActTermId, ExpThes.SelFolder.getAbsolutePath()+File.separatorChar+ActTermId+".rdf.xml", ExpThes.getRoot(), ExpThes.getMainLang());
Thes.Import("Alimnetación", "999", new File("c:\\DATOS\\D\\JHierro\\OPD\\30.rdf.xml"), "ES", "http://OpenProdoc.org/");
setCursor(MainWin.DefCur);
} catch (Exception ex)
    {
    setCursor(MainWin.DefCur);    
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ImportThesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddTerm;
    private javax.swing.JMenuItem AddThesaur;
    private javax.swing.JMenuItem DelTerm;
    private javax.swing.JMenuItem DelThesaur;
    private javax.swing.JLabel DescripLabel;
    private javax.swing.JTextField DescripTextField;
    private javax.swing.JSplitPane DetailsPanel;
    private javax.swing.JMenuItem ExportThes;
    private javax.swing.JMenuItem ImportThes;
    private javax.swing.JLabel LangLabel;
    private javax.swing.JTable LangTable;
    private javax.swing.JTextField LangTextField;
    private javax.swing.JMenuItem ModTerm;
    private javax.swing.JTable NTTable;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTable RTTable;
    private javax.swing.JMenuItem RefreshTerm;
    private javax.swing.JTabbedPane Relations;
    private javax.swing.JLabel SCNLabel;
    private javax.swing.JTextField SCNTextField;
    private javax.swing.JMenuItem SearchTerm1;
    private javax.swing.JMenuItem Select;
    private javax.swing.JMenu Selecting;
    private javax.swing.JCheckBoxMenuItem ShowChild;
    private javax.swing.JCheckBoxMenuItem ShowDetails;
    private javax.swing.JPanel TermAttr;
    private javax.swing.JMenu TermMenu;
    private javax.swing.JMenuItem ThesaurHelp;
    private javax.swing.JMenu ThesaurMenu;
    private javax.swing.JTree TreeTerm;
    private javax.swing.JTable UFTable;
    private javax.swing.JMenuItem UpdateThesaur;
    private javax.swing.JLabel UseLabel;
    private javax.swing.JTextField UseTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel jPanelLang;
    private javax.swing.JPanel jPanelNT;
    private javax.swing.JPanel jPanelRT;
    private javax.swing.JPanel jPanelUF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    //---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontMenu()
{
return (MainWin.getFontMenu());
}
//---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontTree()
{
return (MainWin.getFontTree());
}
//---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontList()
{
return (MainWin.getFontList());
}
//---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontDialog()
{
return (MainWin.getFontDialog());
}
//---------------------------------------------------------------------
/**
 * 
 * @param RecomFileName
 * @param Ext
 * @param Save
 * @return
 */
static public String SelectDestination(String RecomFileName, String Ext, boolean Save)
{
JFileChooser fc = new JFileChooser();
//fc.setDialogTitle("Seleccionar Archivo");
if (Ext!=null)
    fc.setFileFilter(new FileNameExtensionFilter("file "+Ext, Ext));
if (RecomFileName!=null)
    fc.setSelectedFile(new File(RecomFileName));
if (!Save)
    {
    if (fc.showOpenDialog(null)!=JFileChooser.APPROVE_OPTION)
        return("");
    }
else
    {
    if (fc.showSaveDialog(null)!=JFileChooser.APPROVE_OPTION)
        return("");
    }
return(fc.getSelectedFile().getAbsolutePath());
}
//---------------------------------------------------------------------
/**
 * 
 * @param RecomFileName
 * @return
 */
static public String SelectFolderDestination(String RecomFileName)
{
JFileChooser fc = new JFileChooser();
if (RecomFileName!=null)
    fc.setSelectedFile(new File(RecomFileName));
fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
if (fc.showSaveDialog(null)!=JFileChooser.APPROVE_OPTION)
    return("");
return(fc.getSelectedFile().getAbsolutePath());
}
//---------------------------------------------------------------------
private TreeModel getTreeModel()
{
if (TermTreeModel==null)
    {
    PDThesaur RootFolder=null;
    try {
    RootFolder = new PDThesaur(Session);
    RootFolder.Load(getIdLocalRootTerm());
    TreeTerm TF=new TreeTerm(RootFolder);
    DefaultMutableTreeNode RootTreeFolder = new DefaultMutableTreeNode(TF);
    TermTreeModel=new DefaultTreeModel(RootTreeFolder);
    ExpandFold(RootTreeFolder);
    } catch (PDException ex)
        {
        MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
        return(null);
        }
    }
return(TermTreeModel);
}
//---------------------------------------------------------------------
private void ExpandFold(DefaultMutableTreeNode ChildTreeFolder)
{
try {
ChildTreeFolder.removeAllChildren();
PDThesaur Fold= ((TreeTerm) ChildTreeFolder.getUserObject()).getTerm();
HashSet Child =Fold.getListDirectDescendList(Fold.getPDId());
for (Iterator it = Child.iterator(); it.hasNext();)
    {
    String ChildId=(String)it.next();
    if (ChildId.compareTo(Fold.getPDId())==0)
        continue;
    PDThesaur ChildFolder=new PDThesaur(Session);
    ChildFolder.Load(ChildId);
    TreeTerm TFc=new TreeTerm(ChildFolder);
    DefaultMutableTreeNode ChildTreeFolder2=new DefaultMutableTreeNode(TFc);
    DefaultMutableTreeNode ChildTreeFolder3=new DefaultMutableTreeNode(null);
    ChildTreeFolder2.add(ChildTreeFolder3);
    ChildTreeFolder.add(ChildTreeFolder2);
    }
(((TreeTerm) ChildTreeFolder.getUserObject())).setExpanded(true);
TermTreeModel.reload(ChildTreeFolder);
TreeTerm.setPreferredSize(null);
} catch (PDException ex)
    {
    MainWin.Message(MainWin.DrvTT(ex.getLocalizedMessage()));
    }
}
//---------------------------------------------------------------------
/**
 * 
 * @param Title
 * @param FieldName
 * @param ToolTip
 * @param FieldText
 * @return
 */
static public String DialogReadString(String Title, String FieldName, String ToolTip, String FieldText)
{
DialogReadString dialog = new DialogReadString(new javax.swing.JFrame(), true);
dialog.setLocationRelativeTo(null);
dialog.SetVals(Title, FieldName, ToolTip, FieldText);
dialog.setVisible(true);
if (dialog.getReturnStatus() == DialogReadString.RET_CANCEL)
    return null;
else
    return(dialog.getField());
}
//---------------------------------------------------------------------
static private Image getIcon()
{
ImageIcon PDIcon=new ImageIcon("resources/LogoProdoc.jpg");
return PDIcon.getImage();
}
//---------------------------------------------------------------------
private void UpdateTabs(String ActTermId) throws PDException
{
RefreshNT(ActTermId);
RefreshRT(ActTermId);
RefreshLang(ActTermId);
RefreshUF(ActTermId);
}
//----------------------------------------------------------------
private void RefreshRT(String TermId) throws PDException
{
RTMembers = new PDTableModel();
RTMembers.setDrv(MainWin.getSession());
RTMembers.setListFields(PDThesaur.getRecordStructPDThesaur());
HashSet Mem=getTermAct().getListRT(TermId);
if (!Mem.isEmpty())
    RTMembers.setCursor(getTermAct().LoadList(Mem));
else    
    RTMembers.setVector(VEmpty);
RTTable.setModel(RTMembers);
RTTable.getColumnModel().getColumn(0).setMaxWidth(0);
RTTable.getColumnModel().removeColumn(RTTable.getColumnModel().getColumn(0));
}
//----------------------------------------------------------------
private void RefreshLang(String TermId) throws PDException
{
LangMembers = new PDTableModel();
LangMembers.setDrv(MainWin.getSession());
LangMembers.setListFields(PDThesaur.getRecordStructPDThesaur());
HashSet Mem=getTermAct().getListLang(TermId);
if (!Mem.isEmpty())
    LangMembers.setCursor(getTermAct().LoadList(Mem));
else    
    LangMembers.setVector(VEmpty);
LangTable.setModel(LangMembers);
LangTable.getColumnModel().getColumn(0).setMaxWidth(0);
LangTable.getColumnModel().removeColumn(LangTable.getColumnModel().getColumn(0));
}
//----------------------------------------------------------------
private void RefreshNT(String TermId) throws PDException
{
NTMembers = new PDTableModel();
NTMembers.setDrv(MainWin.getSession());
NTMembers.setListFields(PDThesaur.getRecordStructPDThesaur());
HashSet Mem=getTermAct().getListDirectDescendList(TermId);
if (!Mem.isEmpty())
    NTMembers.setCursor(getTermAct().LoadList(Mem));
else    
    NTMembers.setVector(VEmpty);
NTTable.setModel(NTMembers);
NTTable.getColumnModel().getColumn(0).setMaxWidth(0);
NTTable.getColumnModel().removeColumn(NTTable.getColumnModel().getColumn(0));
}
//----------------------------------------------------------------
private void RefreshUF(String TermId) throws PDException
{
UFMembers = new PDTableModel();
UFMembers.setDrv(MainWin.getSession());
UFMembers.setListFields(PDThesaur.getRecordStructPDThesaur());
HashSet Mem=getTermAct().getListUF(TermId);
if (!Mem.isEmpty())
    UFMembers.setCursor(getTermAct().LoadList(Mem));
else    
    UFMembers.setVector(VEmpty);
UFTable.setModel(UFMembers);
UFTable.getColumnModel().getColumn(0).setMaxWidth(0);
UFTable.getColumnModel().removeColumn(UFTable.getColumnModel().getColumn(0));
}
//----------------------------------------------------------------
/** Activates "select mode" for selecting a term
 *  showing a small windows without thesaururs maintenance
 */
public void ModeSelect()
{
ShowDetails(false);
this.setSize(200, 300);
this.ThesaurMenu.setVisible(false);
ShowDetails.setSelected(false);
this.AddTerm.setVisible(false);
this.ModTerm.setVisible(false);
this.DelTerm.setVisible(false);
}
//----------------------------------------------------------------
/**
 * @return the IdLocalRootTerm
 */
public String getIdLocalRootTerm()
{
return IdLocalRootTerm;
}
//----------------------------------------------------------------
/**
 * @param IdLocalRootTerm the IdLocalRootTerm to set
 */
public void setIdLocalRootTerm(String IdLocalRootTerm)
{
this.IdLocalRootTerm = IdLocalRootTerm;
}
//----------------------------------------------------------------
private void ShowDetails(boolean pShowDet)
{
ShowDet=pShowDet;    
if (ShowDet)
    {
    DetailsPanel.setVisible(true);
    jSplitPane1.setDividerLocation(DividerLocTerm);
    }
else
    {    
    DividerLocTerm=jSplitPane1.getDividerLocation();
    jSplitPane1.setDividerLocation(2000);
    DetailsPanel.setVisible(false);
    }
}
//----------------------------------------------------------------
/**
 * @return the TermAct
 */
public PDThesaur getTermAct()
{
return TermAct;
}
//----------------------------------------------------------------
/**
 * @param TermAct the TermAct to set
 */
public void setTermAct(PDThesaur TermAct)
{
this.TermAct = TermAct;
}
//----------------------------------------------------------------
}
