/*
 * OpenProdoc
 * 
 * See the help doc files distributed with
 * this work for additional information regarding copyright ownership.
 * Joaquin Hierro licenses this file to You under:
 * 
 * License GNU GPL v3 http://www.gnu.org/licenses/gpl.html
 * 
 * you may not use this file except in compliance with the License.  
 * Unless agreed to in writing, software is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * author: Joaquin Hierro      2011
 * 
 */

/*
 * MainWin.java
 *
 * Created on 29-ene-2010, 0:52:22
 */

package prodocswing.forms;

import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import prodoc.*;
import prodocswing.PDTableModel;
import prodocswing.TreeFolder;

/**
 *
 * @author jhierrot
 */
public class MainWin extends javax.swing.JFrame
{
static private Font MenuFont=null;
static private Font TreeFont=null;
static private Font ListFont=null;
static private Font DialogFont=null;
private static DriverGeneric Session=null;
static private DefaultTreeModel FoldTreeModel=null;
private static SimpleDateFormat formatterTS = null;
private static SimpleDateFormat formatterDate = null;
private static DefaultFormatterFactory formFacTS = null;
private static DefaultFormatterFactory formFacDate = null;
static private String ActFolderId=PDFolders.ROOTFOLDER;
static private PDTableModel DocsContained;

private PDFolders FoldAct=null;
static private String List=PDFolders.fACL+"/"+PDFolders.fFOLDTYPE+"/"+PDFolders.fPARENTID+"/"+PDFolders.fPDID+"/"+PDFolders.fTITLE+"/"+PDFolders.fPDAUTOR+"/"+PDFolders.fPDDATE;


/**
* @return the Session
*/
public static DriverGeneric getSession()
{
return Session;
}

/** Creates new form MainWin */
public MainWin()
{
initComponents();
DocsTable.setAutoCreateRowSorter(true);
DocsTable.setAutoCreateColumnsFromModel(true);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreeFolder = new javax.swing.JTree();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        SelFolderDesc = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DocsTable = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        FolderMenu = new javax.swing.JMenu();
        AddFold = new javax.swing.JMenuItem();
        DelFold = new javax.swing.JMenuItem();
        ModFold = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        AddFoldAdvanced = new javax.swing.JMenuItem();
        ModFoldAdvanced = new javax.swing.JMenuItem();
        RefreshFold = new javax.swing.JMenuItem();
        SearchFold = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        DocMenu = new javax.swing.JMenu();
        AddDoc = new javax.swing.JMenuItem();
        DelDoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        AddDocAdvanced = new javax.swing.JMenuItem();
        ModDocAdvanced = new javax.swing.JMenuItem();
        RefreshDocs = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        CheckOut = new javax.swing.JMenuItem();
        CheckIn = new javax.swing.JMenuItem();
        CancelCheckout = new javax.swing.JMenuItem();
        ListVersions = new javax.swing.JMenuItem();
        SearchDocs = new javax.swing.JMenuItem();
        OtherMenu = new javax.swing.JMenu();
        PaperBin = new javax.swing.JMenuItem();
        ChangePass = new javax.swing.JMenuItem();
        AdminMenu = new javax.swing.JMenu();
        ACLMenuItem = new javax.swing.JMenuItem();
        GroupMenuItem = new javax.swing.JMenuItem();
        UserMenuItem = new javax.swing.JMenuItem();
        RolMenuItem = new javax.swing.JMenuItem();
        MimeTypeMenuItem = new javax.swing.JMenuItem();
        ReposMenuItem = new javax.swing.JMenuItem();
        ObjDefMenuItem = new javax.swing.JMenuItem();
        AuthentMenuItem = new javax.swing.JMenuItem();
        CustomMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenProDoc 0.1");
        setIconImage(getIcon());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(150);

        TreeFolder.setFont(getFontTree());
        TreeFolder.setModel(getTreeModel());
        TreeFolder.setAlignmentX(0.3F);
        TreeFolder.setAutoscrolls(true);
        TreeFolder.setComponentPopupMenu(FolderMenu.getComponentPopupMenu());
        TreeFolder.setMaximumSize(new java.awt.Dimension(400, 76));
        TreeFolder.setMinimumSize(new java.awt.Dimension(200, 60));
        TreeFolder.setPreferredSize(new java.awt.Dimension(200, 76));
        TreeFolder.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                TreeFolderTreeExpanded(evt);
            }
        });
        TreeFolder.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                TreeFolderValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(TreeFolder);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(24, 48));

        SelFolderDesc.setFont(getFontMenu());
        SelFolderDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane2.setViewportView(SelFolderDesc);

        jSplitPane2.setTopComponent(jScrollPane2);

        DocsTable.setFont(getFontList());
        DocsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DocsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DocsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(DocsTable);

        jSplitPane2.setRightComponent(jScrollPane3);

        jSplitPane1.setRightComponent(jSplitPane2);

        menuBar.setFont(getFontMenu());

        FolderMenu.setText(TT("Folders"));
        FolderMenu.setFont(getFontMenu());

        AddFold.setFont(getFontMenu());
        AddFold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        AddFold.setText(TT("Add"));
        AddFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFoldActionPerformed(evt);
            }
        });
        FolderMenu.add(AddFold);

        DelFold.setFont(getFontMenu());
        DelFold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/del.png"))); // NOI18N
        DelFold.setText(TT("Delete"));
        DelFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelFoldActionPerformed(evt);
            }
        });
        FolderMenu.add(DelFold);

        ModFold.setFont(getFontMenu());
        ModFold.setText(TT("Update"));
        ModFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModFoldActionPerformed(evt);
            }
        });
        FolderMenu.add(ModFold);
        FolderMenu.add(jSeparator2);

        AddFoldAdvanced.setFont(getFontMenu());
        AddFoldAdvanced.setText(TT("Extended_Add"));
        AddFoldAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFoldAdvancedActionPerformed(evt);
            }
        });
        FolderMenu.add(AddFoldAdvanced);

        ModFoldAdvanced.setFont(getFontMenu());
        ModFoldAdvanced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        ModFoldAdvanced.setText(TT("Update_Extended"));
        ModFoldAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModFoldAdvancedActionPerformed(evt);
            }
        });
        FolderMenu.add(ModFoldAdvanced);

        RefreshFold.setFont(getFontMenu());
        RefreshFold.setText(TT("Refresh"));
        RefreshFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshFoldActionPerformed(evt);
            }
        });
        FolderMenu.add(RefreshFold);

        SearchFold.setFont(getFontMenu());
        SearchFold.setText(TT("Search_Folders"));
        SearchFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFoldActionPerformed(evt);
            }
        });
        FolderMenu.add(SearchFold);
        FolderMenu.add(jSeparator5);

        exitMenuItem.setFont(getFontMenu());
        exitMenuItem.setText(TT("Exit"));
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        FolderMenu.add(exitMenuItem);

        menuBar.add(FolderMenu);

        DocMenu.setText(TT("Documents"));
        DocMenu.setFont(getFontMenu());

        AddDoc.setFont(getFontMenu());
        AddDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        AddDoc.setText(TT("Add"));
        AddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDocActionPerformed(evt);
            }
        });
        DocMenu.add(AddDoc);

        DelDoc.setFont(getFontMenu());
        DelDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/del.png"))); // NOI18N
        DelDoc.setText(TT("Delete"));
        DelDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelDocActionPerformed(evt);
            }
        });
        DocMenu.add(DelDoc);
        DocMenu.add(jSeparator3);

        AddDocAdvanced.setFont(getFontMenu());
        AddDocAdvanced.setText(TT("Extended_Add"));
        AddDocAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDocAdvancedActionPerformed(evt);
            }
        });
        DocMenu.add(AddDocAdvanced);

        ModDocAdvanced.setFont(getFontMenu());
        ModDocAdvanced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        ModDocAdvanced.setText(TT("Update_Extended"));
        ModDocAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModDocAdvancedActionPerformed(evt);
            }
        });
        DocMenu.add(ModDocAdvanced);

        RefreshDocs.setFont(getFontMenu());
        RefreshDocs.setText(TT("Refresh"));
        RefreshDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshDocsActionPerformed(evt);
            }
        });
        DocMenu.add(RefreshDocs);
        DocMenu.add(jSeparator4);

        CheckOut.setFont(getFontMenu());
        CheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/checkout.png"))); // NOI18N
        CheckOut.setText("CheckOut");
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });
        DocMenu.add(CheckOut);

        CheckIn.setFont(getFontMenu());
        CheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/checkin.png"))); // NOI18N
        CheckIn.setText("CheckIn");
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });
        DocMenu.add(CheckIn);

        CancelCheckout.setFont(getFontMenu());
        CancelCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelcheckout.png"))); // NOI18N
        CancelCheckout.setText("CancelCheckout");
        CancelCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelCheckoutActionPerformed(evt);
            }
        });
        DocMenu.add(CancelCheckout);

        ListVersions.setFont(getFontMenu());
        ListVersions.setText(TT("List_of_Versions"));
        ListVersions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListVersionsActionPerformed(evt);
            }
        });
        DocMenu.add(ListVersions);

        SearchDocs.setFont(getFontMenu());
        SearchDocs.setText(TT("Search_Documents"));
        SearchDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDocsActionPerformed(evt);
            }
        });
        DocMenu.add(SearchDocs);

        menuBar.add(DocMenu);

        OtherMenu.setText(TT("Other_Tasks"));
        OtherMenu.setFont(getFontMenu());

        PaperBin.setFont(getFontMenu());
        PaperBin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/undel.png"))); // NOI18N
        PaperBin.setText(MainWin.TT("Trash_bin"));
        PaperBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperBinActionPerformed(evt);
            }
        });
        OtherMenu.add(PaperBin);

        ChangePass.setFont(getFontMenu());
        ChangePass.setText(MainWin.TT("Password_change"));
        ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassActionPerformed(evt);
            }
        });
        OtherMenu.add(ChangePass);

        menuBar.add(OtherMenu);

        AdminMenu.setText(TT("Administration"));
        AdminMenu.setFont(getFontMenu());

        ACLMenuItem.setFont(getFontMenu());
        ACLMenuItem.setText("ACL");
        ACLMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACLMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(ACLMenuItem);

        GroupMenuItem.setFont(getFontMenu());
        GroupMenuItem.setText(TT("Groups"));
        GroupMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(GroupMenuItem);

        UserMenuItem.setFont(getFontMenu());
        UserMenuItem.setText(TT("Users"));
        UserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(UserMenuItem);

        RolMenuItem.setFont(getFontMenu());
        RolMenuItem.setText(TT("Roles"));
        RolMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(RolMenuItem);

        MimeTypeMenuItem.setFont(getFontMenu());
        MimeTypeMenuItem.setText(TT("Mime_Types"));
        MimeTypeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MimeTypeMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(MimeTypeMenuItem);

        ReposMenuItem.setFont(getFontMenu());
        ReposMenuItem.setText(TT("Repositories"));
        ReposMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReposMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(ReposMenuItem);

        ObjDefMenuItem.setFont(getFontMenu());
        ObjDefMenuItem.setText(TT("Object_definitions"));
        ObjDefMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjDefMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(ObjDefMenuItem);

        AuthentMenuItem.setFont(getFontMenu());
        AuthentMenuItem.setText(TT("Authenticators"));
        AuthentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthentMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(AuthentMenuItem);

        CustomMenuItem.setFont(getFontMenu());
        CustomMenuItem.setText(TT("Customizations"));
        CustomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(CustomMenuItem);

        menuBar.add(AdminMenu);

        helpMenu.setText(TT("Help"));
        helpMenu.setFont(getFontMenu());

        contentsMenuItem1.setFont(getFontMenu());
        contentsMenuItem1.setText(TT("Contents"));
        contentsMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(contentsMenuItem1);

        aboutMenuItem1.setFont(getFontMenu());
        aboutMenuItem1.setText(TT("About"));
        aboutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem1);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
    Disconnect();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void UserMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UserMenuItemActionPerformed
    {//GEN-HEADEREND:event_UserMenuItemActionPerformed
try {
ListUsers LU = new ListUsers(this, true, new PDUser(getSession()));
LU.setLocationRelativeTo(null);
LU.setVisible(true);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_UserMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
    Disconnect();
    }//GEN-LAST:event_formWindowClosing

    private void MimeTypeMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MimeTypeMenuItemActionPerformed
    {//GEN-HEADEREND:event_MimeTypeMenuItemActionPerformed
try {
ListMimeTypes LMT = new ListMimeTypes(this, true, new PDMimeType(getSession()));
LMT.setLocationRelativeTo(null);
LMT.setVisible(true);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_MimeTypeMenuItemActionPerformed

    private void ACLMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ACLMenuItemActionPerformed
    {//GEN-HEADEREND:event_ACLMenuItemActionPerformed
try {
ListAcl LA = new ListAcl(this, true, new PDACL(getSession()));
LA.setLocationRelativeTo(null);
LA.setVisible(true);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ACLMenuItemActionPerformed

    private void GroupMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GroupMenuItemActionPerformed
    {//GEN-HEADEREND:event_GroupMenuItemActionPerformed
try {
ListGroups LG = new ListGroups(this, true, new PDGroups(getSession()));
LG.setLocationRelativeTo(null);
LG.setVisible(true);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_GroupMenuItemActionPerformed

    private void RolMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RolMenuItemActionPerformed
    {//GEN-HEADEREND:event_RolMenuItemActionPerformed
try {
ListRoles LR = new ListRoles(this, true, new PDRoles(getSession()));
LR.setLocationRelativeTo(null);
LR.setVisible(true);
} catch (Exception ex)  
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_RolMenuItemActionPerformed

    private void ReposMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ReposMenuItemActionPerformed
    {//GEN-HEADEREND:event_ReposMenuItemActionPerformed
try {
ListRepositories LR = new ListRepositories(this, true, new PDRepository(getSession()));
LR.setLocationRelativeTo(null);
LR.setVisible(true);
} catch (Exception ex)  
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ReposMenuItemActionPerformed

    private void TreeFolderTreeExpanded(javax.swing.event.TreeExpansionEvent evt)//GEN-FIRST:event_TreeFolderTreeExpanded
    {//GEN-HEADEREND:event_TreeFolderTreeExpanded
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
if ( ((TreeFolder) TreeFold.getUserObject()).isExpanded())
    return;
ExpandFold(TreeFold);
    }//GEN-LAST:event_TreeFolderTreeExpanded

    private void TreeFolderValueChanged(javax.swing.event.TreeSelectionEvent evt)//GEN-FIRST:event_TreeFolderValueChanged
    {//GEN-HEADEREND:event_TreeFolderValueChanged
try {
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
FoldAct= ((TreeFolder) TreeFold.getUserObject()).getFold();
SelFolderDesc.setText(HtmlDesc(FoldAct));
ActFolderId=FoldAct.getPDId();
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_TreeFolderValueChanged

    private void AddFoldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddFoldActionPerformed
    {//GEN-HEADEREND:event_AddFoldActionPerformed
String NewFoldChild=DialogReadString(TT("Add_Folder"),TT("Folder_name"), TT("Write_Folder_name"), null);
if (NewFoldChild==null || NewFoldChild.length()==0)
    return;
try {
PDFolders Fold=new PDFolders(Session);
Fold.setPDId(ActFolderId);
Fold.CreateChild(NewFoldChild);
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) TreeFolder.getSelectionPath().getLastPathComponent();
ExpandFold(TreeFold);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_AddFoldActionPerformed

    private void DelFoldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DelFoldActionPerformed
    {//GEN-HEADEREND:event_DelFoldActionPerformed
try {
//PDFolders Fold=new PDFolders(Session);
//Fold.setPDId(ActFolderId);
//Fold.delete();
//TreePath ParentFold = (TreePath) TreeFolder.getSelectionPath().getParentPath();
//ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) TreeFolder.getSelectionPath().getLastPathComponent();
PDFolders Fold= ((TreeFolder) TreeFold.getUserObject()).getFold();
DialogEditFold DEF = new DialogEditFold(this, true);
DEF.setLocationRelativeTo(null);
DEF.DelMode();
Fold.LoadFull(ActFolderId);
DEF.setRecord(Fold.getRecord());
DEF.setVisible(true);
if (DEF.isCancel())
    return;
Fold.delete();
TreePath ParentFold = (TreePath) TreeFolder.getSelectionPath().getParentPath();
ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_DelFoldActionPerformed

    private void AddFoldAdvancedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddFoldAdvancedActionPerformed
    {//GEN-HEADEREND:event_AddFoldAdvancedActionPerformed
try {
DialogEditFold DEF = new DialogEditFold(this, true);
DEF.setLocationRelativeTo(null);
DEF.AddMode();
DEF.setAcl(FoldAct.getACL());
DEF.setVisible(true);
if (DEF.isCancel())
    return;
PDFolders Fold=new PDFolders(Session);
Fold.assignValues(DEF.getRecord());
Fold.setParentId(ActFolderId);
Fold.insert();
TreePath ParentFold = (TreePath) TreeFolder.getSelectionPath().getParentPath();
ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_AddFoldAdvancedActionPerformed

    private void ModFoldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModFoldActionPerformed
    {//GEN-HEADEREND:event_ModFoldActionPerformed
try {
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) TreeFolder.getSelectionPath().getLastPathComponent();
PDFolders Fold= ((TreeFolder) TreeFold.getUserObject()).getFold();
String NewTitle=DialogReadString(TT("Update_Folder"),TT("Folder_name"), TT("Write_Folder_name"), Fold.getTitle());
if (NewTitle==null || NewTitle.length()==0)
    return;
Fold.setTitle(NewTitle);
Fold.update();
TreePath ParentFold = (TreePath) TreeFolder.getSelectionPath().getParentPath();
ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ModFoldActionPerformed

    private void ModFoldAdvancedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModFoldAdvancedActionPerformed
    {//GEN-HEADEREND:event_ModFoldAdvancedActionPerformed
try {
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) TreeFolder.getSelectionPath().getLastPathComponent();
PDFolders Fold= ((TreeFolder) TreeFold.getUserObject()).getFold();
DialogEditFold DEF = new DialogEditFold(this, true);
DEF.setLocationRelativeTo(null);
DEF.EditMode();
Fold.LoadFull(Fold.getPDId());
DEF.setRecord(Fold.getRecord());
DEF.setVisible(true);
if (DEF.isCancel())
    return;
Fold.assignValues(DEF.getRecord());
Fold.update();
TreePath ParentFold = (TreePath) TreeFolder.getSelectionPath().getParentPath();
ExpandFold((DefaultMutableTreeNode)ParentFold.getLastPathComponent());
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ModFoldAdvancedActionPerformed

    private void RefreshFoldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RefreshFoldActionPerformed
    {//GEN-HEADEREND:event_RefreshFoldActionPerformed
DefaultMutableTreeNode TreeFold = (DefaultMutableTreeNode) TreeFolder.getSelectionPath().getLastPathComponent();
ExpandFold(TreeFold);
    }//GEN-LAST:event_RefreshFoldActionPerformed

    private void ObjDefMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ObjDefMenuItemActionPerformed
    {//GEN-HEADEREND:event_ObjDefMenuItemActionPerformed
ListObjDef LOD = new ListObjDef(this, true, new PDObjDefs(getSession()));
LOD.setLocationRelativeTo(null);
LOD.setVisible(true);
    }//GEN-LAST:event_ObjDefMenuItemActionPerformed

    private void AddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDocActionPerformed
try {
PDDocs Doc = new PDDocs(getSession());
DialogEditDocReduced MD = new DialogEditDocReduced(this,true);
MD.setRecord(Doc.getRecSum());
MD.AddMode();
MD.setLocationRelativeTo(null);
MD.setVisible(true);
if (MD.isCancel())
    return;
Doc.assignValues(MD.getRecord());
if (MD.SelFile!=null)
    Doc.setFile(MD.SelFile.getAbsolutePath());
else
    throw new PDException("Error_retrieving_file");
Doc.setParentId(ActFolderId);
Doc.insert();
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_AddDocActionPerformed

    private void DelDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelDocActionPerformed
if (DocsTable.getSelectedRow()==-1)
    return;
try {
PDDocs Doc = new PDDocs(getSession());
DialogEditDoc MD = new DialogEditDoc(this,true);
Doc.assignValues(DocsContained.getElement(DocsTable.getSelectedRow()));
Doc.Load(Doc.getPDId());
MD.setRecord(Doc.getRecSum());
MD.DelMode();
MD.setLocationRelativeTo(null);
MD.setVisible(true);
if (MD.isCancel())
    return;
Doc.assignValues(MD.getRecord());
Doc.delete();
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_DelDocActionPerformed

    private void AddDocAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDocAdvancedActionPerformed
try {
PDDocs Doc = new PDDocs(getSession());
DialogEditDoc MD = new DialogEditDoc(this,true);
MD.setRecord(Doc.getRecSum());
MD.AddMode();
MD.setLocationRelativeTo(null);
MD.setVisible(true);
if (MD.isCancel())
    return;
String SelectedType=(String)MD.getRecord().getAttr(PDDocs.fDOCTYPE).getValue();
if (!SelectedType.equalsIgnoreCase(Doc.getDocType()))
    Doc = new PDDocs(getSession(), SelectedType);
Doc.assignValues(MD.getRecord());
if (MD.SelFile!=null)
    Doc.setFile(MD.SelFile.getAbsolutePath());
else
    throw new PDException("Error_retrieving_file");
Doc.setParentId(ActFolderId);
Doc.insert();
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_AddDocAdvancedActionPerformed

    private void ModDocAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModDocAdvancedActionPerformed
if (DocsTable.getSelectedRow()==-1)
    return;
try {
PDDocs Doc = new PDDocs(getSession());
DialogEditDoc MD = new DialogEditDoc(this,true);
Doc.assignValues(DocsContained.getElement(DocsTable.getSelectedRow()));
Doc.LoadFull(Doc.getPDId());
MD.setRecord(Doc.getRecSum());
MD.EditMode();
MD.setLocationRelativeTo(null);
MD.setVisible(true);
if (MD.isCancel())
    return;
Doc.assignValues(MD.getRecord());
Doc.update();
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ModDocAdvancedActionPerformed

    private void RefreshDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshDocsActionPerformed
RefreshDocs();
    }//GEN-LAST:event_RefreshDocsActionPerformed

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
if (DocsTable.getSelectedRow()==-1)
    return;
try {
PDDocs Doc = new PDDocs(getSession());
Doc.assignValues(DocsContained.getElement(DocsTable.getSelectedRow()));
Doc.Checkout();
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_CheckOutActionPerformed

    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
if (DocsTable.getSelectedRow()==-1)
    return;
try {
PDDocs Doc = new PDDocs(getSession());
Doc.assignValues(DocsContained.getElement(DocsTable.getSelectedRow()));
String VersionLabel=DialogReadString(TT("Creating_a_new_version_of_document"), TT("Version_identifier"),  TT("Type_a_version_name_or_identifier"), "");
if (VersionLabel==null)
    return;
if (VersionLabel.length()==0)
    {
    Message(TT("Version_identifier_required"));
    return;
    }
Doc.Checkin(VersionLabel);
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_CheckInActionPerformed

    private void CancelCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelCheckoutActionPerformed
if (DocsTable.getSelectedRow()==-1)
    return;
try {
if (!MessageQuestion(TT("Do_you_want_to_cancel_edition_and_lost_changes")))
    return;
PDDocs Doc = new PDDocs(getSession());
Doc.assignValues(DocsContained.getElement(DocsTable.getSelectedRow()));
Doc.CancelCheckout();
RefreshDocs();
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_CancelCheckoutActionPerformed

    private void PaperBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaperBinActionPerformed
ListDeleted LD = new ListDeleted(this, true);
LD.setLocationRelativeTo(null);
LD.setVisible(true);
    }//GEN-LAST:event_PaperBinActionPerformed

    private void ListVersionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListVersionsActionPerformed
if (DocsTable.getSelectedRow()==-1)
    return;
ListVersions LV = new ListVersions(this, true, DocsContained.getElement(DocsTable.getSelectedRow()));
LV.setLocationRelativeTo(null);
LV.setVisible(true);
    }//GEN-LAST:event_ListVersionsActionPerformed

    private void SearchFoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFoldActionPerformed
SearchFold SF = new SearchFold(this, true);
SF.setLocationRelativeTo(null);
SF.setFoldAct(ActFolderId);
SF.setVisible(true);     
    }//GEN-LAST:event_SearchFoldActionPerformed

    private void SearchDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDocsActionPerformed
SearchDocs SD = new SearchDocs(this, true);
SD.setLocationRelativeTo(null);
SD.setFoldAct(ActFolderId);
SD.setVisible(true);
    }//GEN-LAST:event_SearchDocsActionPerformed

    private void AuthentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthentMenuItemActionPerformed
try {
ListAuthenticators LA = new ListAuthenticators(this, true, new PDAuthenticators(getSession()));
LA.setLocationRelativeTo(null);
LA.setVisible(true);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_AuthentMenuItemActionPerformed

    private void ChangePassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ChangePassActionPerformed
    {//GEN-HEADEREND:event_ChangePassActionPerformed
try {
ChangePassword CP = new ChangePassword(this, true);
CP.setLocationRelativeTo(null);
CP.setVisible(true);
if (CP.isCancel())
    return;
getSession().ChangePassword(getSession().getUser().getName(), CP.getOldPasswordField(), CP.getNewPasswordField1());
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_ChangePassActionPerformed

    private void CustomMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CustomMenuItemActionPerformed
    {//GEN-HEADEREND:event_CustomMenuItemActionPerformed
try {
ListCustom LC = new ListCustom(this, true, new PDCustomization(getSession()));
LC.setLocationRelativeTo(null);
LC.setVisible(true);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
    }//GEN-LAST:event_CustomMenuItemActionPerformed

    private void aboutMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_aboutMenuItem1ActionPerformed
AboutOPD Ab=new AboutOPD(this, rootPaneCheckingEnabled);
Ab.setLocationRelativeTo(null);
Ab.setVisible(true);
Ab.dispose();
    }//GEN-LAST:event_aboutMenuItem1ActionPerformed

    private void contentsMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_contentsMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_contentsMenuItem1ActionPerformed
Execute("help"+OSSep()+getLang()+OSSep()+"MainWin.html");   
    }//GEN-LAST:event_contentsMenuItem1ActionPerformed

    private void DocsTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DocsTableMouseClicked
    {//GEN-HEADEREND:event_DocsTableMouseClicked
if (evt.getClickCount()<2)
    return;
if (DocsTable.getSelectedRow()==-1)
    return;
try {
PDDocs Doc = new PDDocs(getSession());
Doc.assignValues(DocsContained.getElement(DocsTable.getSelectedRow()));
String FileName=Doc.getFile(getTmp());
Execute(FileName);
} catch (Exception ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }

    }//GEN-LAST:event_DocsTableMouseClicked

/**
* @param args the command line arguments
*/
public static void main(String args[])
{
String PropertiesFile;    
if (args.length==0)    
    PropertiesFile="Prodoc.properties";
//    PropertiesFile="e:\\Prodoc\\Varios\\Prodoc_derby.properties";
//    PropertiesFile="/media/Iomega/Prodoc/ProdocInstall/dist/Prodoc.properties";
//    PropertiesFile="/media/Iomega/Prodoc/Varios/Prodoc_derby.properties";
else
    PropertiesFile=args[0];
if (!Connect(PropertiesFile))
    System.exit(0);
java.awt.EventQueue.invokeLater(new Runnable()
    {
    public void run()
        {
        MainWin MW=new MainWin();
        MW.setLocationRelativeTo(null);
        MW.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ACLMenuItem;
    private javax.swing.JMenuItem AddDoc;
    private javax.swing.JMenuItem AddDocAdvanced;
    private javax.swing.JMenuItem AddFold;
    private javax.swing.JMenuItem AddFoldAdvanced;
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem AuthentMenuItem;
    private javax.swing.JMenuItem CancelCheckout;
    private javax.swing.JMenuItem ChangePass;
    private javax.swing.JMenuItem CheckIn;
    private javax.swing.JMenuItem CheckOut;
    private javax.swing.JMenuItem CustomMenuItem;
    private javax.swing.JMenuItem DelDoc;
    private javax.swing.JMenuItem DelFold;
    private javax.swing.JMenu DocMenu;
    private javax.swing.JTable DocsTable;
    private javax.swing.JMenu FolderMenu;
    private javax.swing.JMenuItem GroupMenuItem;
    private javax.swing.JMenuItem ListVersions;
    private javax.swing.JMenuItem MimeTypeMenuItem;
    private javax.swing.JMenuItem ModDocAdvanced;
    private javax.swing.JMenuItem ModFold;
    private javax.swing.JMenuItem ModFoldAdvanced;
    private javax.swing.JMenuItem ObjDefMenuItem;
    private javax.swing.JMenu OtherMenu;
    private javax.swing.JMenuItem PaperBin;
    private javax.swing.JMenuItem RefreshDocs;
    private javax.swing.JMenuItem RefreshFold;
    private javax.swing.JMenuItem ReposMenuItem;
    private javax.swing.JMenuItem RolMenuItem;
    private javax.swing.JMenuItem SearchDocs;
    private javax.swing.JMenuItem SearchFold;
    private javax.swing.JLabel SelFolderDesc;
    private javax.swing.JTree TreeFolder;
    private javax.swing.JMenuItem UserMenuItem;
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem contentsMenuItem1;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

//---------------------------------------------------------------------
private static void EvaluateDef()
{
try {
String FontDef=getSession().getUser().getCustomData().getSwingStyle();
String ListF[]=FontDef.split(",");
MenuFont  =new java.awt.Font(ListF[0], Integer.parseInt(ListF[1]), Integer.parseInt(ListF[2]));
TreeFont  =new java.awt.Font(ListF[3], Integer.parseInt(ListF[4]), Integer.parseInt(ListF[5]));
ListFont  =new java.awt.Font(ListF[6], Integer.parseInt(ListF[7]), Integer.parseInt(ListF[8]));
DialogFont=new java.awt.Font(ListF[9], Integer.parseInt(ListF[10]), Integer.parseInt(ListF[11]));
} catch (Exception ex)
    {
    MenuFont=new java.awt.Font("Arial", 0, 12);
    TreeFont=new java.awt.Font("Arial", 0, 12);
    ListFont=new java.awt.Font("Arial", 0, 12);
    DialogFont=new java.awt.Font("Arial", 0, 12);
    }
}
//---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontMenu()
{
if (MenuFont==null)
    EvaluateDef();
return (MenuFont);
}
//---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontTree()
{
if (TreeFont==null)
    EvaluateDef();
return (TreeFont);
}
//---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontList()
{
if (ListFont==null)
    EvaluateDef();
return (ListFont);
}
//---------------------------------------------------------------------
/**
 * 
 * @return
 */
static public Font getFontDialog()
{
if (DialogFont==null)
    EvaluateDef();
return (DialogFont);
}
//---------------------------------------------------------------------
private PDTableModel getTableModel()
{
return new PDTableModel();
}
//---------------------------------------------------------------------

static private boolean Connect(String PropertiesFile)
{
LoginForm dialog = new LoginForm(new javax.swing.JFrame(), true);
dialog.setLocationRelativeTo(null);
for (int NumRetry = 0; NumRetry < 3; NumRetry++)
    {
    dialog.setVisible(true);
    if (dialog.getReturnStatus() == LoginForm.RET_CANCEL)
        return false;
    try {
        ProdocFW.InitProdoc("PD", PropertiesFile);
        Session = ProdocFW.getSession("PD", dialog.getLogin(), dialog.getPass());
        return(true);
    } catch (PDException ex)
        {
        Message(DrvTT(ex.getLocalizedMessage()));
        }
    }
return false;
}
//---------------------------------------------------------------------
static private void Disconnect()
{
try {
if (getSession()!=null)
    {
    ProdocFW.freeSesion("PD", getSession());
    }
ProdocFW.ShutdownProdoc("PD");
} catch (PDException ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
System.exit(0);
}
//---------------------------------------------------------------------
/**
 * 
 * @param pMessage
 */
static public void Message(String pMessage)
{
DialogInfo DI=new DialogInfo(null, true);
DI.SetMessage(DrvTT(pMessage));
DI.setLocationRelativeTo(null);
DI.setVisible(true);
}
//---------------------------------------------------------------------
/**
 * 
 * @param pMessage to show to the user
 * @return if the user selects OK
 */
static public boolean MessageQuestion(String pMessage)
{
DialogInfoQuestion DI=new DialogInfoQuestion(null, true);
DI.SetMessage(DrvTT(pMessage));
DI.setLocationRelativeTo(null);
DI.setVisible( true);
return (DI.getReturnStatus()==DialogInfoQuestion.RET_OK);
}
//---------------------------------------------------------------------
/**
 * 
 * @param RecomFileName
 * @param Ext
 * @param Save
 * @return
 */
static public String SelectDestination(String RecomFileName, String Ext, boolean Save)
{
JFileChooser fc = new JFileChooser();
//fc.setDialogTitle("Seleccionar Archivo");
if (Ext!=null)
    fc.setFileFilter(new FileNameExtensionFilter("file "+Ext, Ext));
if (RecomFileName!=null)
    fc.setSelectedFile(new File(RecomFileName));
if (!Save)
    {
    if (fc.showOpenDialog(null)!=JFileChooser.APPROVE_OPTION)
        return("");
    }
else
    {
    if (fc.showSaveDialog(null)!=JFileChooser.APPROVE_OPTION)
        return("");
    }
return(fc.getSelectedFile().getAbsolutePath());
}
//---------------------------------------------------------------------
private TreeModel getTreeModel()
{
if (FoldTreeModel==null)
    {
    PDFolders RootFolder=null;
    try {
    RootFolder = new PDFolders(Session);
    RootFolder.Load(PDFolders.ROOTFOLDER);
    TreeFolder TF=new TreeFolder(RootFolder);
    DefaultMutableTreeNode RootTreeFolder = new DefaultMutableTreeNode(TF);
    FoldTreeModel=new DefaultTreeModel(RootTreeFolder);
    ExpandFold(RootTreeFolder);
    } catch (PDException ex)
        {
        Message(DrvTT(ex.getLocalizedMessage()));
        return(null);
        }
    }
return(FoldTreeModel);
}
//---------------------------------------------------------------------
private void ExpandFold(DefaultMutableTreeNode ChildTreeFolder)
{
try {
ChildTreeFolder.removeAllChildren();
PDFolders Fold= ((TreeFolder) ChildTreeFolder.getUserObject()).getFold();
HashSet Child =Fold.getListDirectDescendList(Fold.getPDId());
for (Iterator it = Child.iterator(); it.hasNext();)
    {
    String ChildId=(String)it.next();
    if (ChildId.compareTo(Fold.getPDId())==0)
        continue;
    PDFolders ChildFolder=new PDFolders(Session);
    ChildFolder.LoadFull(ChildId);
    TreeFolder TFc=new TreeFolder(ChildFolder);
    DefaultMutableTreeNode ChildTreeFolder2=new DefaultMutableTreeNode(TFc);
    DefaultMutableTreeNode ChildTreeFolder3=new DefaultMutableTreeNode(null);
    ChildTreeFolder2.add(ChildTreeFolder3);
    ChildTreeFolder.add(ChildTreeFolder2);
    }
(((TreeFolder) ChildTreeFolder.getUserObject())).setExpanded(true);
FoldTreeModel.reload(ChildTreeFolder);
} catch (PDException ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
}
//---------------------------------------------------------------------
static private String FormatDate(Date d)
{
return( getFormatterTS().format(d));
}
//---------------------------------------------------------------------
/**
 * 
 * @param Title
 * @param FieldName
 * @param ToolTip
 * @param FieldText
 * @return
 */
static public String DialogReadString(String Title, String FieldName, String ToolTip, String FieldText)
{
DialogReadString dialog = new DialogReadString(new javax.swing.JFrame(), true);
dialog.setLocationRelativeTo(null);
dialog.SetVals(Title, FieldName, ToolTip, FieldText);
dialog.setVisible(true);
if (dialog.getReturnStatus() == DialogReadString.RET_CANCEL)
    return null;
else
    return(dialog.getField());
}
//---------------------------------------------------------------------
static private Image getIcon()
{
ImageIcon PDIcon=new ImageIcon("resources/LogoProdoc.jpg");
return PDIcon.getImage();
}
//---------------------------------------------------------------------
/**
 * Refresh the list of documents
 * called after changing folder or adding, modifying or deleting a document
 */
private void RefreshDocs()
{
try {
    DocsContained = new PDTableModel();
    DocsContained.setDrv(MainWin.getSession());
    FoldAct.getListDirectDescendList(ActFolderId);
    PDDocs Doc = new PDDocs(getSession());
    DocsContained.setListFields(Doc.getRecordStruct());
    DocsContained.setCursor(Doc.getListContainedDocs(FoldAct.getPDId()));
    DocsTable.setModel(DocsContained);
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(13));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(12));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(11));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(10));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(9));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(8));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(7));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(6));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(5));
    DocsTable.getColumnModel().removeColumn(DocsTable.getColumnModel().getColumn(0));
//   0 4 5 7 8 9 10 11 12
} catch (PDException ex)
    {
    Message(DrvTT(ex.getLocalizedMessage()));
    }
}
//---------------------------------------------------------------------
static int Execute(String Doc)
{
try {
String Order="";
String OS=System.getProperty("os.name");
//System.out.println("OS:"+OS);

// WINDOWS << explorer "path">>
// gnome << gnome-open "path">>
// KDE <<kde-open "path">>
// X <<xdg-open  "path">>
if (OS.contains("Win"))
    Order="explorer ";
else
    Order="xdg-open ";
Process Pr=Runtime.getRuntime().exec(Order+"\""+Doc+"\"", null, null);
/* 
String s = null;
BufferedReader stdInput = new BufferedReader(new InputStreamReader(Pr.getInputStream()));
BufferedReader stdError = new BufferedReader(new InputStreamReader(Pr.getErrorStream()));
while ((s = stdInput.readLine()) != null)
    {
    System.out.println(s);
    }
while ((s = stdError.readLine()) != null)
    {
    System.out.println(s);
    }
 */
} catch (Exception ex)
    {
    Message(ex.getLocalizedMessage());
    }
return(0);
}
//---------------------------------------------------------------------
private String HtmlDesc(PDFolders FoldAct) throws PDException
{
StringBuilder Html=new StringBuilder("<html><b>"+FoldAct.getTitle()+"</b> ("+FoldAct.getFolderType() +") : "+FormatDate(FoldAct.getPDDate())+ "<hr> ACL="+FoldAct.getACL());
Record Rec=FoldAct.getRecSum();
Rec.initList();
Attribute Attr=Rec.nextAttr();
while (Attr!=null)
    {
    if (!List.contains(Attr.getName()))
        {
        Html.append("<br><b>").append(DrvTT(Attr.getUserName())).append("= </b>");
        Html.append(Attr.getValue());
        }
    Attr=Rec.nextAttr();
    }
Html.append("</html>");
return(Html.toString());
}
//---------------------------------------------------------------------
/**
 * 
 * @param Text
 * @return
 */
static public String DrvTT(String Text)
{
if (getSession()==null)
    return( DriverGeneric.DefTT(Text) );
else
    return( getSession().TT(Text) );
}
//----------------------------------------------------------
/**
 * 
 * @param Text
 * @return
 */
static public String TT(String Text)
{
if (getSession()==null)
    return( DriverGeneric.DefTT(Text) );
else
    return( getSession().TT(Text) );
}
//---------------------------------------------------------------------
/**
 * @return the formatterTS
 */
public static SimpleDateFormat getFormatterTS()
{
if (formatterTS==null)
    {
    try {
        formatterTS = new SimpleDateFormat(getSession().getPDCust().getTimeFormat());
    } catch (PDException ex)
        {
        formatterTS = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        }
    }
return formatterTS;
}
//---------------------------------------------------------------------

/**
 * @return the formatterDate
 */
public static SimpleDateFormat getFormatterDate()
{
if (formatterDate==null)
    {
    try {
        formatterDate = new SimpleDateFormat(getSession().getPDCust().getDateFormat());
    } catch (PDException ex)
        {
        formatterDate = new SimpleDateFormat("yyyy-MM-dd");
        }
    }
return formatterDate;
}
//---------------------------------------------------------------------
/**
 * @return the formatTS
 */
public static String getFormatTS()
{
try {
return (getSession().getPDCust().getTimeFormat() );
}  catch (PDException ex)
    {
    return("yyyy-MM-dd HH:mm:ss");
    }
}
//---------------------------------------------------------------------
/**
 * @return the formatDate
 */
public static String getFormatDate()
{
try {
return(getSession().getPDCust().getDateFormat());
} catch (PDException ex)
    {
    return("yyyy-MM-dd");
    }
}
//---------------------------------------------------------------------
/**
 * @return the formFacTS
 * @throws Exception 
 */
public static DefaultFormatterFactory getFormFacTS() throws Exception
{
if (formFacTS==null)
    {
//    formFacTS = new DefaultFormatterFactory(new MaskFormatter(MainWin.getFormatTS()));
    formFacTS = new DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat((MainWin.getFormatTS()))));
    }
return formFacTS;
}
//---------------------------------------------------------------------
/**
 * @return the formFacDate
 * @throws Exception
 */
public static DefaultFormatterFactory getFormFacDate() throws Exception
{
if (formFacDate==null)
    {
//    formFacDate = new DefaultFormatterFactory(new MaskFormatter(MainWin.getFormatDate()));
    formFacDate = new DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat((MainWin.getFormatDate()))));
    }
return formFacDate;
}
//---------------------------------------------------------------------

private String getLang()
{
try {
    return(getSession().getPDCust().getLanguage());
} catch (PDException ex)
    {
    return("EN");
    }
}
//---------------------------------------------------------------------
private String OSSep()
{
return(File.separator);
}
//---------------------------------------------------------------------
static public String getTmp()
{
String Tmp=System.getProperty("java.io.tmpdir");
return(Tmp);  
}
//---------------------------------------------------------------------
}
